### ISSUE TITLE
bug: Can't modify domain and path of ynh app

### ISSUE THREAD

**Issue by artybdrlt** [ketsapiwiq/ansible-yunohost-modules#2]
I may do things in a wrong way but I tried to follow the example in `ynh_app.py`.
Here is the play I'm trying to use: 
```
tasks:
  - name: test module to change domain and path of mattermost
    ynh_app:
      name: "discourse"
      domain: "poclydra.fr"
      settings:
          path: '/forum'
      label: 'Discourse'
      state: present
```
The play runs nicely and doesn't fail but Ansible returns OK each time and doesn't change anything to the domain or path. 
What am I doing wrong?

**Comment by ketsapiwiq** [comment]
@artybdrlt It should be way better now!
Thanks for the tests

**Comment by artybdrlt** [comment]
Okay, I've tried with your newest update:

  - name: Change path of 20euros app (WORKING)
```
    ynh_app:
      name: 20euros
      label: argent
      settings:
          path: /play
```
It's working as expected and as many times as I want!
