### ISSUE TITLE
bug: 'bool' object is not subscriptable\

### ISSUE THREAD

**Issue by artybdrlt** [ketsapiwiq/ansible-yunohost-modules#3]
In my playbook: 

```
  - name: Install apps (LOOP)
    ynh_app:
      name: "{{ item.name }}"
      label: "{{ item.label }}"
      domain: "{{ item.domain }}"
      settings:
          path: "{{ item.path }}"
          is_public: "{{ item.is_public }}"
          admin: "{{ item.admin }}"
    loop: "{{ ynh_app_test }}"
```
In my var file:
```
---
ynh_app_test:
  - name: 20euros
    label: Money
    domain: poclydra.fr
    path: /20euros
    is_public: 0
    admin:

  - name: alltube
    label: yt_dl
    domain: poclydra.fr
    path: /yt_dl
    is_public: 1
    admin:
```
The two apps are installed by the module yet i get an EM:

`failed: [server_dev_01] (item={'name': 'alltube', 'label': 'yt_dl', 'domain': 'poclydra.fr', 'path': '/yt_dl', 'is_public': 1, 'admin': None}) => {"ansible_loop_var": "item", "changed": false, "item": {"admin": null, "domain": "poclydra.fr", "is_public": 1, "label": "yt_dl", "name": "alltube", "path": "/yt_dl"}, "module_stderr": "Shared connection to poc1.communaute.192.168.7.133.nip.io closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/arthur/.ansible/tmp/ansible-tmp-1636715927.7325258-16933-79930130166824/AnsiballZ_ynh_app.py\", line 100, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/arthur/.ansible/tmp/ansible-tmp-1636715927.7325258-16933-79930130166824/AnsiballZ_ynh_app.py\", line 92, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/arthur/.ansible/tmp/ansible-tmp-1636715927.7325258-16933-79930130166824/AnsiballZ_ynh_app.py\", line 41, in invoke_module\r\n    run_name='__main__', alter_sys=True)\r\n  File \"/usr/lib/python3.7/runpy.py\", line 205, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/lib/python3.7/runpy.py\", line 96, in _run_module_code\r\n    mod_name, mod_spec, pkg_name, script_name)\r\n  File \"/usr/lib/python3.7/runpy.py\", line 85, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_ynh_app_payload_qme6rirr/ansible_ynh_app_payload.zip/ansible/modules/ynh_app.py\", line 686, in <module>\r\n  File \"/tmp/ansible_ynh_app_payload_qme6rirr/ansible_ynh_app_payload.zip/ansible/modules/ynh_app.py\", line 682, in main\r\n  File \"/tmp/ansible_ynh_app_payload_qme6rirr/ansible_ynh_app_payload.zip/ansible/modules/ynh_app.py\", line 615, in run_module\r\n  File \"/tmp/ansible_ynh_app_payload_qme6rirr/ansible_ynh_app_payload.zip/ansible/modules/ynh_app.py\", line 205, in _change_setting\r\nTypeError: 'bool' object is not subscriptable\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}`

 What's even weirder is that apps are installed anyway and the permissions are set correctly. I have also tried with true /false but it also get the error and even if I remove the is_public from settings I get this error. 

Do you know what is wrong?

**Comment by ketsapiwiq** [comment]
Thanks, I'll look it up!

There was a first dumb bug, I'm pushing a fix right now.

But it still doesn't seem to correclty change permissions: I suspect it's because I should implement settings such as "admin" and "is_public" differently: because YunoHost handles them differently from other settings, being `permissions`.
Here's some examples that should work until I fix `is_public` and `admin`:
```
- name: Public app
  ynh_app:
    name: dokuwiki
    permissions:
      - visitors
      - all_users
```
```
- name: Private app
  ynh_app:
    name: dokuwiki
 # default value is append: no
    # append: no
    permissions:
      - admin_username
```
