### ISSUE TITLE
Allow handling permissions with `settings.is_public` and `settings.admin`

### ISSUE THREAD

**Issue by ketsapiwiq** [ketsapiwiq/ansible-yunohost-modules#4]
Right now we can use permissions like this:

```
- name: Public app
  ynh_app:
    name: dokuwiki
    permissions:
      - visitors
      - all_users
```
```
- name: Private app
  ynh_app:
    name: dokuwiki
 # default value is append: no
    # append: no
    permissions:
      - admin_username
```
But we should be able to also do:

> In my playbook:
> 
> ```
>   - name: Install apps (LOOP)
>     ynh_app:
>       name: "{{ item.name }}"
>       label: "{{ item.label }}"
>       domain: "{{ item.domain }}"
>       settings:
>           path: "{{ item.path }}"
>           is_public: "{{ item.is_public }}"
>           admin: "{{ item.admin }}"
>     loop: "{{ ynh_app_test }}"
> ```
> 
> In my var file:
> 
> ```
> ---
> ynh_app_test:
>   - name: 20euros
>     label: Money
>     domain: poclydra.fr
>     path: /20euros
>     is_public: 0
>     admin:
> 
>   - name: alltube
>     label: yt_dl
>     domain: poclydra.fr
>     path: /yt_dl
>     is_public: 1
>     admin:
> ```
